### ISSUE TITLE
MacOS dwarf reading on version 2.2.0 not working

### ISSUE THREAD

**Issue by awitten1** [davea42/libdwarf-code#307]
Hi! I think somewhere between version 2.1.0 and 2.2.0, reading dwarf information on MacOS might have been broken.

Everything works on version 2.1.0. 

But on version 2.2.0 I get error:
```
$ ./libdwarf-install/bin/dwarfdump test_dwarf

./libdwarf-install/bin/dwarfdump ERROR:  dwarf_init_path_dl fails.:  DW_DLE_MACHO_CORRUPT_HEADER(486) Incorrect header content. Corrupt DWARF. Attempting to continue.
```

"test_dwarf" is a test c binary I built with `gcc test.c -gdwarf-5 -o test_dwarf`

I built both 2.1.0 and 2.2.0 with `./configure && make && make install`

**Comment by davea42** [comment]
When I try to compile with 
    gcc -gdwarf-5 test.c -o test5
(test is a hello world program).

This on MacOs Tahoe 26.1

the compile fails with
ld: duplicate symbols
linker command failed with exit code 1

If I use plain -g it links and works and dwarfdump works.

So there is something wrong with -gdwarf-5 and gcc
and nothing wrong with dwarfdmp/libdwarf AFAICT.
